### ISSUE TITLE
How to Install this in Debian XFCE? 

### ISSUE THREAD

**Issue by tazihad** [juanramoncastan/xfconnect-indicator#2]
Do I need to install kdeconnect package from KDE? Or How to uninstall this? Can you please write some steps?

**Comment by juanramoncastan** [comment]
To install xfconnect-indicator just go to Code tab and click the green button (at right) and download the zip file.
Extract it, go to the main directory in a terminal and execute:
./INSTALL.sh
this script will ask you for sudo password.
That's all

There is no script to uninstall it so you must to do it manually with:
sudo rm /usr/local/bin/xfconnect-indicator.py
to delete the python script
Next command is to delete images:
sudo rm -R /usr/local/share/xfconnect/
And to delete systemd user service execute:
rm ~/.config/sytemd/user/xfconnect.service

**Comment by juanramoncastan** [comment]
Sorry. There is a component that I've missed in the INSTALL.sh script
xfconnect-indicator.desktop
I will solve as soon as it possible
While you can cp it directly in your .config /autorstart directory

**Comment by juanramoncastan** [comment]
Ok finally I've fixed the installation of autostart launcher and I've created an UNISTALL script.
If you find something wrong let me know.
