### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by everdred** [juanramoncastan/xfconnect-indicator#4]
`dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownInterface: No such interface 'org.kde.kdeconnect.device.battery' at object path '/modules/kdeconnect/devices/t18320nf201'`

**Comment by juanramoncastan** [comment]
Hi.
please context me this error... Whole output
But possibly is beacause in kdeconnect setting the battery monitor plugin is dissabled...
even if this is the problem it wouldn't give you an error, it just must put inactive the submenu "battery"

**Comment by juanramoncastan** [comment]
I think this problem is solved with the last mods i have aplied.

**Comment by everdred** [comment]
Sorry, I haven't used this application in a while. I just updated and am no longer receiving the noted dbus error, but now I get a new one, so I'll open a new issue. Thank you!

**Comment by everdred** [comment]
I was wrong... there's actually no new dbus error after restarting and allowing the application to launch with my Xfce session.

**Comment by juanramoncastan** [comment]
Let me know if there is some problem. Thanks
